[build]
  publish = "public"
  command = "echo build"
  functions = "netlify/functions"

[site]
  name = "hyperliquid-a-plus-demo"

[[redirects]]
 from = "/" 
 to = "https://hyperliquid-a-plus-demo-20260329.netlify.app/" 
 status = 301
